# Default Config: https://github.com/detekt/detekt/blob/main/detekt-core/src/main/resources/default-detekt-config.yml
# Formatting Config: https://github.com/detekt/detekt/blob/main/detekt-formatting/src/main/resources/config/config.yml

config:
  warningsAsErrors: true

complexity:
  LongParameterList:
    ignoreDefaultParameters: true
    ignoreAnnotated: ['Inject', 'Composable']
  TooManyFunctions:
    active: false
  LongMethod:
    ignoreAnnotated: ['Composable']

coroutines:
  GlobalCoroutineUsage:
    active: true

style:
  DataClassShouldBeImmutable:
    active: true
    ignoreAnnotated: ['Table']
  MagicNumber:
    ignoreEnums: true
    ignorePropertyDeclaration: true
    ignoreAnnotated: ['Composable']
  SpacingBetweenPackageAndImports:
    active: true
  UnusedImports:
    active: true
  WildcardImport:
    active: true
  ForbiddenSuppress:
    active: true
    rules: ['MaximumLineLength']

naming:
  FunctionNaming:
    ignoreAnnotated: [ 'Composable' ]
